
import os
username = {'username': os.getenv('striim_username')}
password = {"Discovery":os.getenv('discovery_password'),
            "Dawn": os.getenv('dawn_password'),
            "Bliss": os.getenv('bliss_password'),
            "Breakaway": os.getenv('breakaway_password'),
            "Encore": os.getenv('encore_password'),
            "Epic": os.getenv('epic_password'),
            "Escape": os.getenv('escape_password'),
            "Explorer": os.getenv('explorer_password'),
            "Gem": os.getenv('gem_password'),
            "Getaway": os.getenv('getaway_password'),
            "Grandeur": os.getenv('grandeur_password'),
            "Insignia": os.getenv('insignia_password'),
            "Jade": os.getenv('jade_password'),
            "Joy": os.getenv('joy_password'),
            "Marina": os.getenv('marina_password'),
            "Mariner": os.getenv('mariner_password'),
            "Nautica": os.getenv('nautica_password'),
            "Navigator": os.getenv('navigator_password'),
            "Pearl": os.getenv('pearl_password'),
            "Pride Of America": os.getenv('pride_of_america_password'),
            "Regatta": os.getenv('regatta_password'),
            "Riviera": os.getenv('riviera_password'),
            "Sirena": os.getenv('sirena_password'),
            "Sky": os.getenv('sky_password'),
            "Spirit": os.getenv('spirit_password'),
            "Splendor": os.getenv('splendor_password'),
            "Star": os.getenv('star_password'),
            "Sun": os.getenv('sun_password'),
            "Voyager": os.getenv('voyager_password'),
            "Jewel": os.getenv('jewel_password'),
            "Prima": os.getenv('prima_password'),
            "Vista": os.getenv('vista_password'),
            "Viva": os.getenv('viva_password')}